import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.DefaultComboBoxModel;
import java.awt.Font;

public class StudyPlan extends JFrame {
	private static final long serialVersionUID = 1L;
	//Private variables
	private static CourseQueries CourseQueries; //instance of the CourseQueries class
	private static ArrayList<Course> allCourses;  //array to store all courses
	private static JTextField textField;
	static JTable tableCourses;
	static DefaultTableModel tableModel;
	
	//Constants for table columns
	private static final int ID_COL = 0;
	private static final int NAME_COL = 1;
	private static final int STATUS_STRING_COL = 3;
	private static final int STATUS_COL = 2;
	private static final int SEMESTER_COL = 4;
	private static final int COL_COUNT = 5;
	/********
	 * Constructor for StudyPlan
	 */
	public StudyPlan () {
		super("Personal study planner");//A call to superclass's constructor method to set the title
		CourseQueries = new CourseQueries();// Initializes a CourseQueries object to handle db operations in this session
		
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		getContentPane().setLayout(null); 
		setBounds(0,0,842,507); 
		setLocationRelativeTo(null); 
		
		//GUI elements (code generated by WindowBuilder)
		
		// button for removing course from the db and study plan
		JButton btnRemoveCourse = new JButton("Remove selected");
		btnRemoveCourse.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				CourseQueries.removeCourse((int)tableCourses.getModel().getValueAt((tableCourses.getSelectedRow()), ID_COL));
				populateTable();
			}
		});
		btnRemoveCourse.setBounds(549, 397, 269, 43);
		getContentPane().add(btnRemoveCourse);
		
		// button for adding the course to the db study plan
		JButton btnAddCourse = new JButton("Add a course");
		btnAddCourse.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				getCourse();
				populateTable();
			}
		});
		btnAddCourse.setBounds(10, 25, 265, 43);
		getContentPane().add(btnAddCourse);
		
		// adds scroll pane for displaying table in it
		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(10, 143, 808, 208);
		getContentPane().add(scrollPane);
		
		//button for marking selected course as completed/not completed and updating it in db
		JButton btnMarkCompletednotCompleted = new JButton("Mark selected as completed / not completed");
		btnMarkCompletednotCompleted.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				markStatus();
				populateTable();
				}
				});
		btnMarkCompletednotCompleted.setBounds(267, 397, 272, 43);
		getContentPane().add(btnMarkCompletednotCompleted);
		
		// table for displaying planned courses and manipulating them
		tableModel = new DefaultTableModel(
				new Object[1][COL_COUNT],  
				new String[] {"ID", "Course Name","","Status","Planned Semester"} // Set the column names
			);
		tableCourses = new JTable();
		scrollPane.setViewportView(tableCourses);//to display tableCourses added to the scrollPane view port 
		tableCourses.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		tableCourses.setModel(tableModel);
		
		//information label how to update planned semester
		JLabel lblToUpdate = new JLabel("* To change Planned Semester click on it, choose a new one from the dropdown menu and press OK");
		lblToUpdate.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblToUpdate.setBounds(10, 361, 616, 26);
		getContentPane().add(lblToUpdate);
		
		//button for printing content of the table
		JButton btnPrint = new JButton("Print");
		btnPrint.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Print();
			}
		});
		btnPrint.setBounds(10, 397, 247, 43);
		getContentPane().add(btnPrint);
		
		//combobox to select courses by completion and show them the table
		JComboBox comboBoxCompletion = new JComboBox();
		comboBoxCompletion.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent e) {
			
				if(e.getStateChange() == ItemEvent.SELECTED) {//if new item is selected
					if (e.getItem().equals("completed")) {//if selected item is "completed"
						populateTableStatus(true);//execute populateTableStatus method with true as an input
					}
					else if (e.getItem().equals("not completed")) {//if selected item is "not completed" 
						populateTableStatus(false);//execute populateTableStatus method with false as an input
					}
					else {
						populateTable();//if other option selected execute populateTable method
					}
                }
			}
		});
		comboBoxCompletion.setModel(new DefaultComboBoxModel(new String[] {"All", "completed", "not completed"}));
		comboBoxCompletion.setBounds(395, 107, 138, 26);
		getContentPane().add(comboBoxCompletion);
		
		//information label 
		JLabel lblSelect = new JLabel("Filter by status");
		lblSelect.setBounds(295, 107, 90, 26);
		getContentPane().add(lblSelect);
		
		//comboBbox to select courses by planned semester and show them the table
		JComboBox comboBoxSemesterPlanned = new JComboBox();
		comboBoxSemesterPlanned.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent e) {
				if(e.getStateChange() == ItemEvent.SELECTED) {
					
					if (e.getItem().equals("All")) {//if selected item is "all" execute populateTable
						populateTable();
					}
					else {
						populateTableSemester((String)e.getItem());//tales a selected item as an input for the populateTableSemester method and executes the method
					}
                }
			}
		});
		comboBoxSemesterPlanned.setModel(new DefaultComboBoxModel(new String[] {"All", "Autumn 2018", "Spring 2019", "Summer 2019", "Autumn 2019", "Spring 2020", "Summer 2020"}));
		comboBoxSemesterPlanned.setBounds(671, 107, 138, 26);
		getContentPane().add(comboBoxSemesterPlanned);
		
		//information label
		JLabel lblShow = new JLabel("Filter by semester");
		lblShow.setBounds(552, 107, 109, 26);
		getContentPane().add(lblShow);
		
		//textfield for the search by name button
		textField = new JTextField();
		textField.setBounds(10, 107, 138, 26);
		getContentPane().add(textField);
		textField.setColumns(10);
		
		//button for searching courses in the database by name or part of the name
		JButton btnSearchByName = new JButton("Search by name");
		btnSearchByName.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				populateTableName(textField.getText()); //Search button clicked -> search courses in the database
				textField.setText("");
			}
		});
		btnSearchByName.setBounds(147, 107, 128, 26);
		getContentPane().add(btnSearchByName);
		
		//information label about usage of filters
		JLabel lblOnluOneFilter = new JLabel("* Only one filter can be used at the same time");
		lblOnluOneFilter.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblOnluOneFilter.setBounds(10, 78, 529, 18);
		getContentPane().add(lblOnluOneFilter);
		
		//button for showing all courses in the table
		JButton btnShowAll = new JButton("Show all");
		btnShowAll.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				populateTable();
			}
		});
		btnShowAll.setBounds(295, 25, 244, 43);
		getContentPane().add(btnShowAll);
		
		//if user clicks on table cell in the "Planned Semester" column new panel will show up for updating the planned semester in db and table
		tableCourses.addMouseListener(new java.awt.event.MouseAdapter() {
		    @Override
		    public void mouseClicked(java.awt.event.MouseEvent evt) {
		    	int row = tableCourses.rowAtPoint(evt.getPoint());
		        int col = tableCourses.columnAtPoint(evt.getPoint());
		        if (row >= 0 && col == 2) {//if event occurs in the third row 
		        	getNewSemester();
		        	populateTable();
		        }
		    }
		});
		
		//Makes ID and Status columns hidden
		tableCourses.removeColumn(tableCourses.getColumnModel().getColumn(STATUS_COL));
		tableCourses.removeColumn(tableCourses.getColumnModel().getColumn(ID_COL));
	}
	//main method
	public static void main(String[] args) {
		JFrame frame = new StudyPlan();
		frame.setVisible(true);
		populateTable();
	}
	/*
	 * Method that gets new course from user and inserts it in the db
	 */
	private void getCourse(){
		JPanel myPanel = new JPanel(); //option panel that appears when user clicks on add course button
		
		JTextField name = new JTextField(15);// field for the course name
		
		String semesterChoise[]= {"Autumn 2018","Spring 2019","Summer 2019", "Autumn 2019","Spring 2020","Summer 2020"}; //options for the planned semester
		JComboBox  semester= new JComboBox (semesterChoise);

		myPanel.add(new JLabel("Course name:"));
		myPanel.add(name);
		
	    myPanel.add(new JLabel("Planned semester:"));
	    myPanel.add(semester);
	    
	    int result = JOptionPane.showConfirmDialog(null, myPanel, "Enter course information", JOptionPane.OK_CANCEL_OPTION);
	    
	    if (result == JOptionPane.OK_OPTION) {	 //if user clicks OK - executes	addCourse method
	    	CourseQueries.addCourse(name.getText(), (String)semester.getSelectedItem());
	    }
	}
	/*
	 * Method that gets new planned semester from user and updates it in the db
	 */
	private void getNewSemester(){
		JPanel myPanel = new JPanel(); //option panel that appears when user clicks on the cell planed semester
		
		String semesterChoise[]= {"Autumn 2018","Spring 2019","Summer 2019", "Autumn 2019","Spring 2020","Summer 2020"}; //options for the planned semester
		JComboBox  semester= new JComboBox (semesterChoise);
		
	    myPanel.add(new JLabel("Choose new Planned Semester:"));
	    myPanel.add(semester);
	    
	    int result = JOptionPane.showConfirmDialog(null, myPanel, "Update semester", JOptionPane.OK_CANCEL_OPTION);
	    
	    if (result == JOptionPane.OK_OPTION) {	  //if user clicks OK - execute updateSemester method  	

	    CourseQueries.updateSemester((String)semester.getSelectedItem(), (int)tableCourses.getModel().getValueAt((tableCourses.getSelectedRow()), ID_COL));
	    }
	}
	/*
	 * Method that gets all courses from the db and displays them in the table
	 */
	public static void populateTable() {
		Course currentCourse;
		allCourses= CourseQueries.getAllCourses();//executes getAllCourses method and gets ArrayList containing Course objects
		tableModel.setRowCount(allCourses.size());//sets number of rows in the table equals to allCourses size
		
		for (int row=0; row<allCourses.size(); row++){ //allCourses.size() returns the amount of items in the allCourses list
			currentCourse = allCourses.get(row); // get an course from the ArrayList allCourses
			//for each course sets in the table values
			tableCourses.getModel().setValueAt(currentCourse.getID(), row, ID_COL);
			tableCourses.getModel().setValueAt(currentCourse.getName(), row, NAME_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatus(), row, STATUS_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatusString(), row, STATUS_STRING_COL);
			tableCourses.getModel().setValueAt(currentCourse.getSemester(), row, SEMESTER_COL);
		}
	}
	/*
	 * Method that gets courses by status from the db and displays them in the table. 
	 */
	public static void populateTableStatus(boolean status) {
		Course currentCourse;
		allCourses= CourseQueries.getAllByStatus(status);
		tableModel.setRowCount(allCourses.size());
		
		for (int row=0; row<allCourses.size(); row++){ //allCourses.size() returns the amount of items in the allCourses list
			currentCourse = allCourses.get(row); // get an course from the ArrayList allCourses
			
			tableCourses.getModel().setValueAt(currentCourse.getID(), row, ID_COL);
			tableCourses.getModel().setValueAt(currentCourse.getName(), row, NAME_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatus(), row, STATUS_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatusString(), row, STATUS_STRING_COL);
			tableCourses.getModel().setValueAt(currentCourse.getSemester(), row, SEMESTER_COL);
		}
	}
	/*
	 * Method that gets courses by semester from the db and displays them in the table. 
	 */
	public static void populateTableSemester(String status) {
		Course currentCourse;
		allCourses= CourseQueries.getAllBySemester(status);
		tableModel.setRowCount(allCourses.size());
		
		for (int row=0; row<allCourses.size(); row++){ //allCourses.size() returns the amount of items in the allCourses list
			currentCourse = allCourses.get(row); // get an course from the ArrayList allCourses
			
			tableCourses.getModel().setValueAt(currentCourse.getID(), row, ID_COL);
			tableCourses.getModel().setValueAt(currentCourse.getName(), row, NAME_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatus(), row, STATUS_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatusString(), row, STATUS_STRING_COL);
			tableCourses.getModel().setValueAt(currentCourse.getSemester(), row, SEMESTER_COL);
		}
	}
	/*
	 * Method that gets courses by name or part of the name from the db and displays them in the table. 
	 */
	public static void populateTableName(String name) {
		Course currentCourse;
		allCourses= CourseQueries.getAllByName(name);
		tableModel.setRowCount(allCourses.size());
		
		for (int row=0; row<allCourses.size(); row++){ //allCourses.size() returns the amount of items in the allCourses list
			currentCourse = allCourses.get(row); // get an course from the ArrayList allCourses
			
			tableCourses.getModel().setValueAt(currentCourse.getID(), row, ID_COL);
			tableCourses.getModel().setValueAt(currentCourse.getName(), row, NAME_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatus(), row, STATUS_COL);
			tableCourses.getModel().setValueAt(currentCourse.getStatusString(), row, STATUS_STRING_COL);
			tableCourses.getModel().setValueAt(currentCourse.getSemester(), row, SEMESTER_COL);
		}
	}
	/*
	 * Method that prints courses displayed in the table. 
	 */
	public static void Print() {
		try {
	          MessageFormat headerFormat = new MessageFormat("Page {0}");
	          MessageFormat footerFormat = new MessageFormat("- {0} -");
	          tableCourses.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
	        } catch (PrinterException pe) {
	          System.err.println("Error printing: " + pe.getMessage());
	        }
	}
	/*
	 * Method that updates status of the course selected by user if mark as completed/not  completed button is clicked. updateStatus method executed with the opposite value of boolean of the selected course and ID of the course from the selected row
	 */
	private void markStatus() {
		CourseQueries.updateStatus(!(Boolean.parseBoolean(tableCourses.getModel().getValueAt(tableCourses.getSelectedRow(), STATUS_COL).toString())) ,(int) tableCourses.getModel().getValueAt((tableCourses.getSelectedRow()), ID_COL));
	}
}
